In [1]:
import os
import numpy as np 
import pandas as pd 

# Machine Learning model specific
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, confusion_matrix,classification_report,ConfusionMatrixDisplay

# Ploting routine
from matplotlib import pyplot as plt

GENRES = ['blues', 'classical', 'country', 'disco', 'hiphop','jazz', 'metal', 'pop', 'reggae', 'rock'] 
root_path = "/kaggle/input/datasets/akashkumbhakar"
folder_name = "blues-10000-csv"
file_name = "blues-10000.csv"

from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
secret_value_0 = user_secrets.get_secret("kgg_key")
secret_value_1 = user_secrets.get_secret("kgg_user")
secret_value_2 = user_secrets.get_secret("WANDB_API_KEY")


import warnings
warnings.filterwarnings("ignore")
print("✅")

✅

# Loading Model

In [2]:
import kagglehub

# Download latest version
path = kagglehub.model_download("akashkumbhakar/svc/scikitLearn/default")
print("Path to model files : ", path)
print("✅ model downloaded.")

Path to model files :  /kaggle/input/models/akashkumbhakar/svc/scikitlearn/default/1
✅ model downloaded.

In [3]:
import joblib
model_path = "/kaggle/input/models/akashkumbhakar/svc/scikitlearn/default/1/SVC.pkl"
pipeline_path = "/kaggle/input/models/akashkumbhakar/svc/scikitlearn/default/1/StandardScaler.pkl"
model = joblib.load(model_path)
pipeline = joblib.load(pipeline_path)
print("✅ Path to model file:", model_path)
print("✅ Path to pipeline file", pipeline_path)

✅ Path to model file: /kaggle/input/models/akashkumbhakar/svc/scikitlearn/default/1/SVC.pkl
✅ Path to pipeline file /kaggle/input/models/akashkumbhakar/svc/scikitlearn/default/1/StandardScaler.pkl

# Test features  and submission

In [4]:
path_to_test_set = "/kaggle/input/datasets/akashkumbhakar/test-tabular-48-3020-csv/test-tabular-48-3020.csv"
test_data = pd.read_csv(path_to_test_set)
x_test = test_data[list(test_data.columns)[1:]]
print("✅ Submission test dataset loaded.")

✅ Submission test dataset loaded.

In [5]:
test_data.head(1)

,song_id,centroid_mean,centroid_var,bandwidth_mean,bandwidth_var,rolloff_mean,rolloff_var,rms,zcr,mfcc_mean1,...,mfcc_var11,mfcc_var12,mfcc_var13,mfcc_var14,mfcc_var15,mfcc_var16,mfcc_var17,mfcc_var18,mfcc_var19,mfcc_var20
0,1,3268.9927,594401.2,3201.1045,110939.14,692.76776,15111.783,0.145979,0.138835,-89.442215,...,112.00832,90.796295,81.18788,87.126465,85.315895,75.585144,79.78585,79.401115,76.06769,61.599792

In [6]:
x_test.head(1)

,centroid_mean,centroid_var,bandwidth_mean,bandwidth_var,rolloff_mean,rolloff_var,rms,zcr,mfcc_mean1,mfcc_mean2,...,mfcc_var11,mfcc_var12,mfcc_var13,mfcc_var14,mfcc_var15,mfcc_var16,mfcc_var17,mfcc_var18,mfcc_var19,mfcc_var20
0,3268.9927,594401.2,3201.1045,110939.14,692.76776,15111.783,0.145979,0.138835,-89.442215,-2.046966,...,112.00832,90.796295,81.18788,87.126465,85.315895,75.585144,79.78585,79.401115,76.06769,61.599792

In [7]:
sample_dir = "/kaggle/input/jan-2026-dl-gen-ai-project/messy_mashup/sample_submission.csv"
sample_sub = pd.read_csv(sample_dir)
print("✅ Sample Submission dataset loaded.")
sample_sub['genre']

✅ Sample Submission dataset loaded.

0            jazz
1           blues
2       classical
3             pop
4           disco
          ...
3015          pop
3016        blues
3017         jazz
3018         rock
3019       reggae
Name: genre, Length: 3020, dtype: object

In [8]:
x_test_transform = pipeline.transform(x_test)
y_pred = model.predict(x_test_transform)
sample_sub['genre'] = y_pred
print("✅")

✅

In [9]:
sample_sub['genre'].value_counts()

genre
hiphop       496
reggae       446
jazz         429
blues        399
pop          305
disco        251
classical    207
metal        194
rock         151
country      142
Name: count, dtype: int64

In [10]:
sample_sub.to_csv('submission.csv',index=False)
if os.path.exists("/kaggle/working/submission.csv"):
    print("✅ Submission.csv created successfully.")

✅ Submission.csv created successfully.